name: Browser Bot Sync

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    
    - uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install Dependencies
      run: |
        npm install
        npx playwright install chromium # تنصيب متصفح كروم

    - name: Run Human Bot
      run: node browser_bot.js

    - name: Commit & Push
      run: |
        git config --global user.name "BrowserBot"
        git config --global user.email "bot@pharma.ai"
        git add banned.csv
        git diff --quiet && git diff --staged --quiet || (git commit -m "🇪🇺 EU Data Sync" && git push)
